In [38]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

In [33]:
df = pd.read_csv("base_datos_2008.csv", nrows = 100000)

In [3]:
#5 primeros valores de la columna ArrDelay
df["ArrDelay"].head()

0   -14.0
1     2.0
2    14.0
3    -6.0
4    34.0
Name: ArrDelay, dtype: float64

In [4]:
#Obtener de la fila 100 a la 109
df[100:110]

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
100,2008,1,3,4,826.0,825,930.0,925,WN,136,...,2.0,16.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
101,2008,1,3,4,2118.0,2015,2224.0,2115,WN,219,...,3.0,17.0,0,NaN,0,17.0,0.0,6.0,0.0,46.0
102,2008,1,3,4,1818.0,1740,1916.0,1840,WN,391,...,2.0,10.0,0,NaN,0,20.0,0.0,0.0,0.0,16.0
103,2008,1,3,4,650.0,650,748.0,750,WN,670,...,3.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
104,2008,1,3,4,2146.0,2055,2250.0,2155,WN,815,...,3.0,13.0,0,NaN,0,4.0,0.0,4.0,0.0,47.0
105,2008,1,3,4,2241.0,1910,2340.0,2010,WN,1072,...,3.0,13.0,0,NaN,0,114.0,0.0,0.0,0.0,96.0
106,2008,1,3,4,1409.0,1355,1513.0,1500,WN,1328,...,2.0,12.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
107,2008,1,3,4,1100.0,1050,1157.0,1155,WN,1586,...,2.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
108,2008,1,3,4,1306.0,1250,1406.0,1355,WN,1838,...,2.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
109,2008,1,3,4,1726.0,1630,1832.0,1740,WN,2284,...,2.0,18.0,0,NaN,0,1.0,0.0,0.0,0.0,51.0

In [5]:
#Obtener todos aquellos que se  hayan retrasado menos de 60 min 
df[df["ArrDelay"]<60].head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,926.0,930,1054.0,1100,WN,1746,...,3.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0

In [6]:
#Obtener los datos donde el origen sea ATL y se haya retrasado por mas de 60 min
df[(df["Origin"]=="ATL")&(df["ArrDelay"]>60)].head()

Empty DataFrame
Columns: [Year, Month, DayofMonth, DayOfWeek, DepTime, CRSDepTime, ArrTime, CRSArrTime, UniqueCarrier, FlightNum, TailNum, ActualElapsedTime, CRSElapsedTime, AirTime, ArrDelay, DepDelay, Origin, Dest, Distance, TaxiIn, TaxiOut, Cancelled, CancellationCode, Diverted, CarrierDelay, WeatherDelay, NASDelay, SecurityDelay, LateAircraftDelay]
Index: []

[0 rows x 29 columns]

In [7]:
df[df.Origin.isin(["HOU","ATL"])].head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
3269,2008,1,4,5,1910.0,1910,2025.0,2025,WN,823,...,6.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3270,2008,1,4,5,1345.0,1345,1453.0,1500,WN,901,...,3.0,14.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3271,2008,1,4,5,736.0,735,839.0,850,WN,957,...,3.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3272,2008,1,4,5,1603.0,1550,1647.0,1635,WN,231,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3273,2008,1,4,5,2105.0,2105,2151.0,2150,WN,570,...,7.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [8]:
#donde ArrDelay tiene valores vacios
df[pd.isna(df["ArrDelay"])].head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
178,2008,1,3,4,NaN,700,NaN,830,WN,126,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
373,2008,1,3,4,NaN,1100,NaN,1215,WN,1146,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
399,2008,1,3,4,NaN,905,NaN,1025,WN,469,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
401,2008,1,3,4,NaN,1620,NaN,1740,WN,618,...,NaN,NaN,1,C,0,NaN,NaN,NaN,NaN,NaN
415,2008,1,3,4,NaN,1930,NaN,2035,WN,2528,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN

In [9]:
len(df[pd.isna(df["ArrDelay"])])

1302

In [10]:
df["HoursDelay"] = round(df["ArrDelay"]/60)

In [11]:
df["HoursDelay"].head()

0   -0.0
1    0.0
2    0.0
3   -0.0
4    1.0
Name: HoursDelay, dtype: float64

In [12]:
del(df["HoursDelay"])

In [13]:
df.drop(["Diverted","Cancelled","Year"], axis = 1)

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,...,Dest,Distance,TaxiIn,TaxiOut,CancellationCode,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1,3,4,2003.0,1955,2211.0,2225,WN,335,N712SW,...,TPA,810,4.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,3,4,754.0,735,1002.0,1000,WN,3231,N772SW,...,TPA,810,5.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1,3,4,628.0,620,804.0,750,WN,448,N428WN,...,BWI,515,3.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN
3,1,3,4,926.0,930,1054.0,1100,WN,1746,N612SW,...,BWI,515,3.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1,3,4,1829.0,1755,1959.0,1925,WN,3920,N464WN,...,BWI,515,3.0,10.0,NaN,2.0,0.0,0.0,0.0,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1,25,5,2204.0,1935,106.0,2257,XE,7676,N11181,...,OKC,866,4.0,17.0,NaN,0.0,0.0,0.0,0.0,129.0
99996,1,26,6,1933.0,1935,2234.0,2257,XE,7676,N16170,...,OKC,866,4.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN
99997,1,27,7,2047.0,1935,2400.0,2257,XE,7676,N12167,...,OKC,866,6.0,18.0,NaN,23.0,0.0,0.0,0.0,40.0
99998,1,28,1,1956.0,1935,2308.0,2257,XE,7676,N16170,...,OKC,866,5.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN
99999,1,29,2,1938.0,1935,2308.0,2257,XE,7676,N11176,...,OKC,866,5.0,41.0,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df.drop(range(0,100000)).head()

Empty DataFrame
Columns: [Year, Month, DayofMonth, DayOfWeek, DepTime, CRSDepTime, ArrTime, CRSArrTime, UniqueCarrier, FlightNum, TailNum, ActualElapsedTime, CRSElapsedTime, AirTime, ArrDelay, DepDelay, Origin, Dest, Distance, TaxiIn, TaxiOut, Cancelled, CancellationCode, Diverted, CarrierDelay, WeatherDelay, NASDelay, SecurityDelay, LateAircraftDelay]
Index: []

[0 rows x 29 columns]

In [15]:
#2 dataframes se pueden unir con append si tienen las mismas columnas
#df1.append(df2)

In [16]:
df.groupby(by="DayOfWeek")["ArrDelay"].describe()

             count       mean        std   min   25%  50%   75%    max
DayOfWeek
1          14349.0   4.568960  29.047008 -56.0  -9.0 -3.0   9.0  431.0
2          14471.0   0.446479  21.617710 -48.0 -10.0 -4.0   5.0  360.0
3          14504.0  -1.646511  18.464538 -48.0 -11.0 -5.0   3.0  422.0
4          16774.0  13.387922  38.490537 -45.0  -7.0  2.0  19.0  486.0
5          14350.0   7.684948  28.156892 -52.0  -7.0  0.0  14.0  364.0
6          11172.0   2.069280  27.866895 -49.0 -11.0 -4.0   6.0  500.0
7          13078.0  12.190625  41.925311 -57.0  -9.0  0.0  16.0  367.0

In [17]:
df.groupby(by="DayOfWeek")["ArrDelay"].mean()

DayOfWeek
1     4.568960
2     0.446479
3    -1.646511
4    13.387922
5     7.684948
6     2.069280
7    12.190625
Name: ArrDelay, dtype: float64

In [18]:
df.groupby(by="DayOfWeek")[["ArrDelay","DepDelay"]].mean()

            ArrDelay   DepDelay
DayOfWeek
1           4.568960   9.141704
2           0.446479   5.192300
3          -1.646511   3.680816
4          13.387922  16.511031
5           7.684948  12.067975
6           2.069280   8.080861
7          12.190625  17.135919

In [19]:
(df[df.Origin.isin(["ATL","HOU"])]).groupby(by = ["DayOfWeek","Origin"])["ArrDelay"].mean()

DayOfWeek  Origin
1          HOU        1.767764
2          HOU        1.624348
3          HOU        3.026178
4          HOU       21.047535
5          HOU        6.853448
6          HOU       -0.967172
7          HOU        7.842629
Name: ArrDelay, dtype: float64

In [20]:
df.dropna()

Empty DataFrame
Columns: [Year, Month, DayofMonth, DayOfWeek, DepTime, CRSDepTime, ArrTime, CRSArrTime, UniqueCarrier, FlightNum, TailNum, ActualElapsedTime, CRSElapsedTime, AirTime, ArrDelay, DepDelay, Origin, Dest, Distance, TaxiIn, TaxiOut, Cancelled, CancellationCode, Diverted, CarrierDelay, WeatherDelay, NASDelay, SecurityDelay, LateAircraftDelay]
Index: []

[0 rows x 29 columns]

In [21]:
df.dropna(thresh=25)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0
6,2008,1,3,4,1937.0,1830,2037.0,1940,WN,509,...,3.0,7.0,0,NaN,0,10.0,0.0,0.0,0.0,47.0
11,2008,1,3,4,1644.0,1510,1845.0,1725,WN,1333,...,6.0,8.0,0,NaN,0,8.0,0.0,0.0,0.0,72.0
16,2008,1,3,4,1452.0,1425,1640.0,1625,WN,675,...,7.0,8.0,0,NaN,0,3.0,0.0,0.0,0.0,12.0
18,2008,1,3,4,1323.0,1255,1526.0,1510,WN,4,...,4.0,9.0,0,NaN,0,0.0,0.0,0.0,0.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99987,2008,1,17,4,2004.0,1935,2313.0,2257,XE,7676,...,5.0,14.0,0,NaN,0,0.0,0.0,0.0,0.0,16.0
99988,2008,1,18,5,2016.0,1935,2344.0,2257,XE,7676,...,4.0,35.0,0,NaN,0,11.0,0.0,6.0,0.0,30.0
99994,2008,1,24,4,1950.0,1935,2332.0,2257,XE,7676,...,5.0,52.0,0,NaN,0,0.0,0.0,20.0,0.0,15.0
99995,2008,1,25,5,2204.0,1935,106.0,2257,XE,7676,...,4.0,17.0,0,NaN,0,0.0,0.0,0.0,0.0,129.0
99997,2008,1,27,7,2047.0,1935,2400.0,2257,XE,7676,...,6.0,18.0,0,NaN,0,23.0,0.0,0.0,0.0,40.0

In [22]:
df.dropna(thresh= len(df.columns)-2)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0
6,2008,1,3,4,1937.0,1830,2037.0,1940,WN,509,...,3.0,7.0,0,NaN,0,10.0,0.0,0.0,0.0,47.0
11,2008,1,3,4,1644.0,1510,1845.0,1725,WN,1333,...,6.0,8.0,0,NaN,0,8.0,0.0,0.0,0.0,72.0
16,2008,1,3,4,1452.0,1425,1640.0,1625,WN,675,...,7.0,8.0,0,NaN,0,3.0,0.0,0.0,0.0,12.0
18,2008,1,3,4,1323.0,1255,1526.0,1510,WN,4,...,4.0,9.0,0,NaN,0,0.0,0.0,0.0,0.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99987,2008,1,17,4,2004.0,1935,2313.0,2257,XE,7676,...,5.0,14.0,0,NaN,0,0.0,0.0,0.0,0.0,16.0
99988,2008,1,18,5,2016.0,1935,2344.0,2257,XE,7676,...,4.0,35.0,0,NaN,0,11.0,0.0,6.0,0.0,30.0
99994,2008,1,24,4,1950.0,1935,2332.0,2257,XE,7676,...,5.0,52.0,0,NaN,0,0.0,0.0,20.0,0.0,15.0
99995,2008,1,25,5,2204.0,1935,106.0,2257,XE,7676,...,4.0,17.0,0,NaN,0,0.0,0.0,0.0,0.0,129.0
99997,2008,1,27,7,2047.0,1935,2400.0,2257,XE,7676,...,6.0,18.0,0,NaN,0,23.0,0.0,0.0,0.0,40.0

In [23]:
df.dropna(subset=["CancellationCode"])

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
178,2008,1,3,4,NaN,700,NaN,830,WN,126,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
373,2008,1,3,4,NaN,1100,NaN,1215,WN,1146,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
399,2008,1,3,4,NaN,905,NaN,1025,WN,469,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
401,2008,1,3,4,NaN,1620,NaN,1740,WN,618,...,NaN,NaN,1,C,0,NaN,NaN,NaN,NaN,NaN
415,2008,1,3,4,NaN,1930,NaN,2035,WN,2528,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98862,2008,1,27,7,NaN,1920,NaN,2045,XE,53,...,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN
98915,2008,1,24,4,NaN,1105,NaN,1349,XE,531,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
99615,2008,1,5,6,NaN,1545,NaN,1711,XE,73,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
99878,2008,1,22,2,NaN,620,NaN,802,XE,7673,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
99991,2008,1,21,1,NaN,1935,NaN,2257,XE,7676,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN

In [24]:
#correlaciones

In [25]:
df.dropna(inplace = True, subset = ["ArrDelay","DepDelay"])

In [26]:
np.corrcoef(df["ArrDelay"], df["DepDelay"])

array([[1.       , 0.9422735],
       [0.9422735, 1.       ]])

In [27]:
df.drop(inplace = True , columns = ["Year","Cancelled","Diverted","Month"])

In [28]:
df.corr()

,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Distance,TaxiIn,TaxiOut,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
DayofMonth,1.000000,-0.118851,-0.001168,0.003749,-0.004445,-0.001941,0.072588,0.004568,-0.006886,0.000893,0.027501,0.007231,-0.006686,-0.012618,0.040429,-0.061650,0.055178,0.111780,-0.012357,0.079725
DayOfWeek,-0.118851,1.000000,0.031111,0.024400,0.021947,0.027785,-0.039560,0.015945,0.017744,0.014324,0.085299,0.098220,0.017525,0.034878,0.000337,0.031015,0.008769,0.001660,0.024726,0.079787
DepTime,-0.001168,0.031111,1.000000,0.985504,0.796903,0.852191,0.023409,-0.069542,-0.065937,-0.065054,0.232415,0.257259,-0.056849,0.029098,-0.068401,0.029925,-0.018628,-0.128269,-0.022763,0.229938
CRSDepTime,0.003749,0.024400,0.985504,1.000000,0.795609,0.862782,0.023789,-0.074644,-0.070060,-0.069232,0.180684,0.202200,-0.061167,0.024048,-0.075218,-0.015536,-0.057462,-0.149643,-0.025722,0.227241
ArrTime,-0.004445,0.021947,0.796903,0.795609,1.000000,0.887002,0.011193,0.013706,0.016936,0.018445,0.076353,0.091164,0.024675,0.044000,-0.062210,-0.027949,-0.033068,-0.067516,-0.005993,-0.050018
CRSArrTime,-0.001941,0.027785,0.852191,0.862782,0.887002,1.000000,0.014385,0.025615,0.032250,0.030644,0.142571,0.171454,0.042641,0.042752,-0.061937,-0.004882,-0.049083,-0.119460,-0.016722,0.171666
FlightNum,0.072588,-0.039560,0.023409,0.023789,0.011193,0.014385,1.000000,0.024159,0.025279,0.021619,-0.001017,0.002810,0.017180,0.007277,0.023976,-0.020801,0.004887,0.002978,-0.007659,-0.002957
ActualElapsedTime,0.004568,0.015945,-0.069542,-0.074644,0.013706,0.025615,0.024159,1.000000,0.983501,0.992457,-0.013101,0.020641,0.963610,0.183375,0.167747,0.021032,0.039746,0.208190,0.014323,-0.076740
CRSElapsedTime,-0.006886,0.017744,-0.065937,-0.070060,0.016936,0.032250,0.025279,0.983501,1.000000,0.989002,-0.088450,0.003833,0.979863,0.134687,0.070776,0.047632,0.016538,0.056008,0.015098,-0.039098
AirTime,0.000893,0.014324,-0.065054,-0.069232,0.018445,0.030644,0.021619,0.992457,0.989002,1.000000,-0.051250,0.004760,0.971304,0.126607,0.058028,0.031140,0.023489,0.118158,0.017114,-0.071480
ArrDelay,0.027501,0.085299,0.232415,0.180684,0.076353,0.142571,-0.001017,-0.013101,-0.088450,-0.051250,1.000000,0.942274,-0.081415,0.130874,0.277640,0.302390,0.267780,0.277161,-0.005642,0.756030
DepDelay,0.007231,0.098220,0.257259,0.202200,0.091164,0.171454,0.002810,0.020641,0.003833,0.004760,0.942274,1.000000,0.009683,0.057272,0.119163,0.328748,0.233300,0.079642,-0.005033,0.790627
Distance,-0.006686,0.017525,-0.056849,-0.061167,0.024675,0.042641,0.017180,0.963610,0.979863,0.971304,-0.081415,0.009683,1.000000,0.114718,0.057072,0.051182,0.007648,0.027524,0.015335,-0.025544
TaxiIn,-0.012618,0.034878,0.029098,0.024048,0.044000,0.042752,0.007277,0.183375,0.134687,0.126607,0.130874,0.057272,0.114718,1.000000,0.050636,-0.023489,0.074326,0.255261,-0.003483,-0.037674
TaxiOut,0.040429,0.000337,-0.068401,-0.075218,-0.062210,-0.061937,0.023976,0.167747,0.070776,0.058028,0.277640,0.119163,0.057072,0.050636,1.000000,-0.041822,0.064286,0.426727,-0.011322,-0.026671
CarrierDelay,-0.061650,0.031015,0.029925,-0.015536,-0.027949,-0.004882,-0.020801,0.021032,0.047632,0.031140,0.302390,0.328748,0.051182,-0.023489,-0.041822,1.000000,-0.064598,-0.104465,-0.028104,-0.129563
WeatherDelay,0.055178,0.008769,-0.018628,-0.057462,-0.033068,-0.049083,0.004887,0.039746,0.016538,0.023489,0.267780,0.233300,0.007648,0.074326,0.064286,-0.064598,1.000000,0.039809,-0.009468,-0.023564
NASDelay,0.111780,0.001660,-0.128269,-0.149643,-0.067516,-0.119460,0.002978,0.208190,0.056008,0.118158,0.277161,0.079642,0.027524,0.255261,0.426727,-0.104465,0.039809,1.000000,-0.011626,-0.111834
SecurityDelay,-0.012357,0.024726,-0.022763,-0.025722,-0.005993,-0.016722,-0.007659,0.014323,0.015098,0.017114,-0.005642,-0.005033,0.015335,-0.003483,-0.011322,-0.028104,-0.009468,-0.011626,1.000000,-0.025623
LateAircraftDelay,0.079725,0.079787,0.229938,0.227241,-0.050018,0.171666,-0.002957,-0.076740,-0.039098,-0.071480,0.756030,0.790627,-0.025544,-0.037674,-0.026671,-0.129563,-0.023564,-0.111834,-0.025623,1.000000

In [29]:
corr = round(df.corr(),3)
corr.style.background_gradient()